[Feat/#4] 뱃지 부분 UI 구현
UMC-1-Footprint/Footprint-iOS pull request #10
Opened 2022-08-29 09:29 UTC by 513sojin

## 📍 *Pull requests*

⛳️ **작업한 브랜치**
- feature/#4

📁 **작업한 내용**

- 뱃지 부분 UI 구현하였습니다 

## 📢 참고 사항

- 리액토킷은 아직 사용하지 않았습니다 (....)
- 피드백 달게 받겠습니다요 . . UI밖에 안짰지만 , , , ,,

## 📸 스크린샷
|기능|스크린샷|
|:--:|:--:|
| | ![Simulator Screen Shot - iPhone 13 mini - 2022-08-29 at 18 18 43](https://user-images.githubusercontent.com/54045865/187169600-7639e91d-a447-4102-ac59-1aa72c07fa4c.png) |

## 👣 관련 이슈
- Resolved: #4

2022-08-29 09:39 UTC, 513sojin commented on FootprintIOS/FootprintIOS/Sources/View/Badge/BadgeView.swift
> +        $0.textColor = .white
질문이 있숴요

선언 부분에서는 딱 선언만 하고 
밑에 setProperty 이 함수에서 이 부분들을 마저 정의해주는 걸까요 ?!

2022-08-29 09:41 UTC, 0inn commented on FootprintIOS/FootprintIOS/Sources/View/Badge/BadgeView.swift
> +        $0.textColor = .white
영모님 방식대로 말하는 걸까요 ?

2022-08-29 09:42 UTC, 513sojin commented on FootprintIOS/FootprintIOS/Sources/View/Badge/BadgeView.swift
> +        $0.textColor = .white
네넴 맞아여 이건 그냥 개인 취향일까요 ?!?!

2022-08-29 09:44 UTC, 0inn commented on FootprintIOS/FootprintIOS/Sources/View/Badge/BadgeView.swift
> +        $0.textColor = .white
음 개인 취향일 것 같은데 저는 선언부에 다 선언해주는게 가독성이 좋더라고요.
만약에 하나의 방식으로 통합하고 싶으면 회의 때 논의해보면 좋을 것 같아요 ~!

2022-08-29 09:49 UTC, 0inn approved these changes
토딘씨 수고했서요 ~ 뱃찌 이뿌네요 😊

2022-08-29 09:49 UTC, 0inn commented on FootprintIOS/FootprintIOS/Sources/ViewController/MyPage/Badge/BadgeViewController.swift
> +        return CGSize(width: cellWidth, height: cellHeight)
기기대응까지 야무지게 ... 좋아요

2022-08-29 09:49 UTC, 0inn commented on FootprintIOS/FootprintIOS/Sources/View/Badge/BadgeView.swift
> +        $0.register(BadgeListViewCell.self, forCellWithReuseIdentifier: BadgeListViewCell.identifier)
선언부에 register 등록할 수 있었네요. 몰랐써여 ㅎㅎ

2022-08-29 10:03 UTC, mooyoung2309 requested changes
브랜치 변경해서 확인해봤는데, 코드 잘 작성하셨고, 모델도 더미로 사용하신게 너무 좋았습니다 !

몇가지 누락된 부분만 수정해주셨으면 합니다 ! 감사합니다.

2022-08-29 10:03 UTC, annapo99 commented on FootprintIOS/FootprintIOS/Sources/View/Badge/BadgeView.swift
> +        $0.register(BadgeListViewCell.self, forCellWithReuseIdentifier: BadgeListViewCell.identifier)
```swift
forCellWithReuseIdentifier: String(describing: BadgeListViewCell.self)
```
static 변수로 id를 선언해도 되지만, 요렇게 해서도 사용 가능합니다 !

2022-08-29 10:03 UTC, annapo99 commented on FootprintIOS/FootprintIOS/Sources/View/Badge/BadgeView.swift
> +
빈칸 없애주시면 감사하겠습니다 ! (꼽주는거 아님 .. 진짜 죄송)

2022-08-29 10:03 UTC, annapo99 commented on FootprintIOS/FootprintIOS/Sources/ViewController/MyPage/Badge/BadgeViewController.swift
> +    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
파일은 BadgeViewController이고, extension은 BadgeView이고, delegate는 BadgeView에서 self로 연결되어 있는 구조가 옳은지 고민입니다.

BadgeView가 재사용 될 가능성이 없다면, 뷰컨에 컴포넌트를 선언하고. 뷰컨에 extension을 따로 빼두어서 delegate를 연결하는건 어떻게 생각하시나요 ?

2022-08-29 10:03 UTC, annapo99 commented on FootprintIOS/FootprintIOS/Sources/View/Badge/Cell/BadgeListViewCell.swift
> +
네이밍 통일 문제인데, BadgeListCollectionViewCell 로 변경하는거에 대해서 어떻게 생각하시나요 ?

CVC는 피하고 싶지만, LVC는 검색할때 잘 안잡힐 것 같다는 생각 뿐입니다..

2022-08-29 10:03 UTC, annapo99 commented on FootprintIOS/FootprintIOS/Sources/ViewController/MyPage/MyPageViewController.swift
> +        pageButton.rx
super 클래스 호출이 빠져 있습니다 !

2022-08-29 10:03 UTC, mooyoung2309 commented on FootprintIOS/FootprintIOS/Sources/View/Badge/Cell/BadgeListViewCell.swift
> +        badgeImage.snp.makeConstraints {
```suggestion
    override func setupLayout() {
        super.setupLayout()
        
        badgeImage.snp.makeConstraints {
```

2022-08-29 10:03 UTC, mooyoung2309 commented on FootprintIOS/FootprintIOS/Sources/View/Badge/BadgeView.swift
> +        badgeListCollectionView.delegate = self
```suggestion
    override func setupDelegate() {
        super.setupDelegate()
        
        badgeListCollectionView.delegate = self
```

2022-08-29 10:03 UTC, mooyoung2309 commented on FootprintIOS/FootprintIOS/Sources/ViewController/MyPage/MyPageViewController.swift
> +        setNavigationBarTitleText("마이페이지")
super 클래스 추가해주세요 !

2022-08-29 10:44 UTC, 513sojin commented on FootprintIOS/FootprintIOS/Sources/ViewController/MyPage/Badge/BadgeViewController.swift
> +    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
원래는 BadgeView에 extension을 뒀었는데 뷰컨에서 관리되는게 좋다던게 생각나서 뷰컨에 복붙 하던 바람에 , ,  난리가 났네여

밑에처럼 바꾸는게 말해준 방향이 맞을까여 ?!?
// BadgeViewController.swift
```
extension BadgeViewController: UICollectionViewDelegateFlowLayout { }
override func setupDelegate() {
        badgeView.badgeListCollectionView.delegate = self
        badgeView.badgeListCollectionView.dataSource = self
    }
```

2022-08-29 10:45 UTC, 513sojin commented on FootprintIOS/FootprintIOS/Sources/View/Badge/Cell/BadgeListViewCell.swift
> +
BadgeListCollectionViewCell 로 변경하는게 훨 나아보입니다 ㅎ.ㅎ 핃백 감사해욧

2022-08-30 03:57 UTC, mooyoung2309 approved these changes
고생많으셨습니다. 최고에요 ! 아프실텐데 몸조리잘하세요 ~~

2022-08-30 06:41 UTC, merged