[Feat/#19] 네트워크 레이어 구축
UMC-1-Footprint/Footprint-iOS pull request #22
Opened 2022-09-19 09:54 UTC by 513sojin

## 📍 *Pull requests*

⛳️ **작업한 브랜치**
- feat/#19

📁 **작업한 내용**
네트워크 레이어를 구축했습니다.
RxSwift를 사용했습니다. 
ㄴ 피드백 받습니다.

![스크린샷 2022-09-19 오후 6 36 40](https://user-images.githubusercontent.com/54045865/190990036-5967fd5d-c273-45e3-8290-1c0a78ee548d.png)

APIEnvironment , APIError, BaseModel, HTTPMethod 파일은 스윽 보면 이해가 될겁니다 !
살짝 유심히 봐야될 파일은 `APIManager`, `EndPoint` 파일입니다  (.swift 파일을 말하고 있습니다. 쓰기 귀찮으니까 다 생략할거임)

**1.`Foundation/APIManager`**
`APIManager` 파일에 있는 request함수는 실제 서버 통신을 하는 함수입니다. 요 친구를 작성하기 위해서 많은 enum들을 정의했습니다 흑 
![스크린샷 2022-09-19 오후 6 53 38](https://user-images.githubusercontent.com/54045865/190992803-d71bbff6-8242-4730-bcc8-58547eb0b279.png)

**2.`Foundation/EndPoint`**
`EndPoint` 파일에는 `NetworkRequest`를 리턴하는 함수가 있는데, 
![스크린샷 2022-09-19 오후 6 42 54](https://user-images.githubusercontent.com/54045865/190991029-d31e21ca-bd75-4f73-8c3b-82cd48718493.png)

여기서 정의된 `NetworkRequest`에 있는 `createNetworkRequest` 함수를 통해 실제 함수에서 사용될 urlRequest를 리턴해줍니다
![스크린샷 2022-09-19 오후 6 47 02](https://user-images.githubusercontent.com/54045865/190991724-04be9915-98d9-4c37-9dce-826650f3424d.png)

**3.`Test/TestEndPoint`**
기능? 페이지 단위로 폴더를 만들계획인데, 그 단위마다 `어쩌구EndPoint.swift` 파일을 만들어주세요
여기 파일에서는 사용될 httpMethod나 header에 들어갈 body, url등을 정의해주고 있습니다

api마다 enum에 case를 추가해서 작성하면 저의 의도대로 진행될 것 같습니다요

![스크린샷 2022-09-19 오후 6 48 37](https://user-images.githubusercontent.com/54045865/190991994-f96bc91e-c6dd-4df9-be1d-eb0e2aaf077a.png)

## 📢 참고 사항
- 서버 통신 참고하고 싶으면 Network/Test 폴더를 보면 됩니당. 사용은 ViewController/Test/TestVC.swift 파일에서 했습니다
- **테스트용으로 해본거라 발자국에서 사용할 baseModel이랑은 차이가 있어서 TestAPIManager 파일을 새롭게 만들었는데 실제 사용할 때는 새로 안만들어도 됩니다** 
- header에 토큰이 들어가는 경우는 아직 구현해두지 않았습니다요 ,, 어차피 소셜 로그인 해야되니까 겸사겸사 다음 PR에 반영해두겠습니다. 

## 👣 관련 이슈
- Resolved: #19

2022-09-19 10:04 UTC, mooyoung2309 requested changes
일단은 막아두겠는데, 너무 고생많으셨습니다 .. 🥺 네트워크가 사실 쉽지 않고 백엔드의 영역이라고 생각해요. 프론트는 예쁘게 보이는게 전부라고 생각합니다. 뒤가 어떻게 동작 되든 간에, 보이는 것만 집중하는 역할이 아닐까요 .. ? (대충 짜셨다는 뜻은 아닙니다.. )

APIManger의 request 함수는 어떤 소스보고 참고 하셨는지 링크가 있을까요 ? 한번 확인해보고 싶습니다 !

2022-09-19 10:04 UTC, mooyoung2309 commented on FootprintIOS/FootprintIOS/Sources/Network/Foundation/APIEnvironment.swift
> +            return "https://jsonplaceholder.typicode.com/users"
해당 주소는, 외부에 공개되면 좋지 않아보입니다.. 아마도 xxconfig 설정을 빼두는게 좋아보이는데,, 우선은 pr을 위해서라면 빈값으로 바꾸는것이 좋아보입니다 !

2022-09-19 13:01 UTC, mooyoung2309 requested changes

2022-09-19 13:01 UTC, annapo99 commented on FootprintIOS/FootprintIOS/Sources/Network/Foundation/APIManager.swift
> +    func request<T: Decodable>(_ request: NetworkRequest) -> Observable<T?> {
해당 함수에서 BaseModel 자체가 nil을 리턴하는 케이스 가 있을까요 ? (궁금)

2022-09-19 13:01 UTC, annapo99 commented on FootprintIOS/FootprintIOS/Sources/Network/Foundation/EndPoint.swift
> +
request에 쿼리스트링을 넣을때는 어떻게 처리하실지 궁금합니다.

XXXadress/user?id=10

2022-09-20 05:23 UTC, mooyoung2309 commented on FootprintIOS/FootprintIOS/Sources/Network/Foundation/NetworkRequest.swift
> +//  Footprint-iOSTests
별건 아닌데,, Tests가 잘못 포함되어있는 것 같습니다 .. ! 아마도 Tuist 설정오류 (그때 카페에서 확인했던 문제 ?) 인것같은데,, 저도 가끔 이렇습니당..

2022-09-20 06:02 UTC, 513sojin commented on FootprintIOS/FootprintIOS/Sources/Network/Foundation/APIManager.swift
> +    func request<T: Decodable>(_ request: NetworkRequest) -> Observable<T?> {
음 . . .api 를 다 뜯어보진 않았지만 사실 없을 것 같기두 합니다

2022-09-20 07:45 UTC, 513sojin commented on FootprintIOS/FootprintIOS/Sources/Network/Foundation/EndPoint.swift
> +
밑에는 TestEndPoint.swift 에 있는 내용인데요
쿼리 들어가는 경우 case 에 추가해두고 URL 가져오는 함수에서 밑에와 같이 사용해주려고 합니다
이 내용 물어보는게 맞나욥

```swift 
enum TestEndPoint {
    case testAPI
    case postTestAPI(String) // 여기 
} 

extension TestEndPoint: EndPoint {

    func getURL(environment: APIEnvironment) -> String {
        switch self {
        case .testAPI:
            return "\(environment.baseURL)"
        case .postTestAPI(let user):
            return "\(environment.baseURL)/user?=\(user)" // 여기
        }
    }
}
```

2022-09-20 08:57 UTC, 513sojin commented on FootprintIOS/FootprintIOS/Sources/Network/Foundation/NetworkRequest.swift
> +//  Footprint-iOSTests
폴더에는 잘 들어간것 같은데 왜그럴까요 . . 하암

2022-09-20 09:00 UTC, 513sojin commented
@mooyoung2309 참고한 자료는 여기에 링크 두겠습니닷 https://life-shelter.tistory.com/357

2022-09-21 03:12 UTC, mooyoung2309 approved these changes
고생하셨습니다 !

2022-09-21 03:32 UTC, merged