[Feat/#47] 네트워크 레이어 수정 및 로그인 api 연결
UMC-1-Footprint/Footprint-iOS pull request #51
Opened 2022-12-19 05:41 UTC by 513sojin

## 📍 *Pull requests*

⛳️ **작업한 브랜치**
- feat/#47

📁 **작업한 내용**

- 네트워크 레이어 수정 
- 기존에 있던 api test관련 파일 및 폴더 삭제
- 로그인 구현 

## 📢 참고 사항

- 키체인 관리하는 파일 따로 만들었습니다
- request, response 마다 model을 따로 만들어두었습니다

## 👣 관련 이슈
- Resolved: #47

2022-12-19 08:08 UTC, 0inn reviewed
고생하셨슴다 . . URLSession으로 구성하시느라 . . ㅎㅎ 최고 . .
서버 열심히 붙여보겠습니다 ~ ! 하하

2022-12-19 08:08 UTC, 0inn commented on FootprintIOS/FootprintIOS/Sources/Network/Login/LoginEndPoint.swift
> +            return Enviroment.apiBaseURL + "/users/auth/login"
p3;

baseURL은 plist에 넣어서 관리하면 좋을 것 같습니다.
추후에 앱 릴리즈하려면 숨기는 게 좋을 것 같아서요 . . !

2022-12-19 08:08 UTC, 0inn commented on FootprintIOS/FootprintIOS/Sources/Network/Foundation/BaseModel.swift
>  }
p1;

제가 아직 서버를 돌려보지 않아서 모르겠지만 . . 
서버 통신 실패시에도 result값이 넘어오나요 ?

2022-12-19 08:08 UTC, 0inn commented on FootprintIOS/FootprintIOS/Sources/Network/Foundation/APIManager.swift
> +                observable.onNext(responseData as! T)
p3;

APIManager
``` Swift
let responseData = try? JSONDecoder().decode(BaseModel<T>.self, from: data) else { }
//
observable.onNext(responseData.result as? T)
```

요런식으로 수정하면 BaseModel<>을 중복해서 작성하지 않아도 될 것 같아 보입니다 !

LoginManager
```
func loginAPI(userId: String, userName: String, userEmail: String, providerType: ProviderType) -> Observable<LoginResponseModel>
```

2022-12-19 12:31 UTC, mooyoung2309 requested changes
고생많으셨습니다..! 

네트워크 레이어는 완전히 로직적인 부분이어서 모두가 사용하기에 최대한 꼼꼼하게 보려고 노력했는데.. 너무 부담이 있다면 언제든지 편하게 도움을 요청하면 빠르게 달려가겠슴니다 .. !!

우선은 혹시나 머지될까바 머지를 막아둘텐데 ,, 댓글달아주시면 계속해서 확인바로하겠습니다 ! 고생하셨습니다..

2022-12-19 12:31 UTC, annapo99 commented on FootprintIOS/FootprintIOS/Sources/Config/KeyChain.swift
> +
p3; struct여야 하는 이유가 있을까요 ?

2022-12-19 12:31 UTC, annapo99 commented on FootprintIOS/FootprintIOS/Sources/Config/KeyChain.swift
> +
p5; 해당 로직은 KeyChainService로 관리해도 좋을 것 같습니다.

이거는 당장 예시가 없어서 바꿀필요는 없어보이는데, accessToken이 바뀌었을때 이벤트를 방출한다거나 하는 로직을 추가해서 좀 더 활용을 높일 수도 있어보입니다 .. !

2022-12-19 12:31 UTC, annapo99 commented on FootprintIOS/FootprintIOS/Sources/Network/Foundation/APIManager.swift
>                    let url = URL(string: encodedURL) else {
p3;

여기에 함수에서 모든 request가 날라가게되는데, 여기쯤에 Request 프린트문을 두어서 로그를 찍도록 하는게 좋아보입니다 ..!
request를 날리기 직전에 request 로그와 response를 받기 직전에 response 로그를 찍히는게 좋아 보입니다 . 로그 형태는 대충 print문으로 해두고 나중에 필요시에 고도화시키는 걸로 하는것도 괜찮아보여요

2022-12-19 12:31 UTC, mooyoung2309 commented on FootprintIOS/FootprintIOS/Sources/Network/Login/LoginManager.swift
> +
p3; 로직 관련 코드는 class로 관리하는게 좋아보입니다. 

찾아본결과;
[Apple Developer](https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes)
애플 공식문서에서는 값 관련한 데이터 처리에서는 기본적으로 구조체 형식을 사용하고

[Swift Language Guide](https://docs.swift.org/swift-book/LanguageGuide/ClassesAndStructures.html#//apple_ref/doc/uid/TP40014097-CH13-XID_108)
스위프트 문서에서는 기본적인 class의 사용을 권장하고 있습니다.

[stackoverflow](https://stackoverflow.com/questions/24232799/why-choose-struct-over-class) 여기서 이 둘을 비교하는 답변이 있는데 .. 나중에 읽어보시면 꽤 도움이 될것같습니다.

2022-12-19 12:31 UTC, mooyoung2309 commented on FootprintIOS/FootprintIOS/Sources/Network/Login/LoginManager.swift
> +    let apiService: APIManager
p5; Manager, Handler, Service 모두 혼용 되고 있는데, 각각 어떤 역할을 하는걸로 생각하신건지 궁금합니다 ..!

2022-12-19 12:31 UTC, mooyoung2309 commented on FootprintIOS/FootprintIOS/Sources/Network/Login/LoginManager.swift
> +        self.apiService = apiService
p3; APIManager 라는 이친구가 필수적이고, 모든 API 로직에서 공요해야하는 클래스 타입이라면 아래와 같이 리펙토링할 수 있어보입니다. 네트워크 서비스 타입에서 apiManager를 강제하고, NetworkService에서 APIManager.shared의 싱글톤을 참조하고 LoginService에서 NetworkService를 상속받고, LoginServiceType을 상속받아서 구현하면 관리가 편해보입니다.

```swift
protocol NetworkServiceType {
    api: APIManager { get }
}

class NetworkService: NetworkServiceType {
  api: APIManager = APIManager.shared
}

enum LoginEvent {
    case login(LoginResponseModel)
}

protocol LoginServiceType {
  var disposedBag: DisposedBag { get }
  var event: PublishSubject<LoginEvent> { get }
  func loginAPI(userId: String, userName: String, userEmail: String, providerType: ProviderType) -> Observable<BaseModel<LoginResponseModel>>
}

class LoginService: NetworkService, LoginServiceType {
  let disposedBag = DisposedBag()
  let event = PublishSubject<LoginEvent>()

    func loginAPI(userId: String, userName: String, userEmail: String, providerType: ProviderType) -> Observable<BaseModel<LoginResponseModel>> {
        let endPoint = LoginEndPoint
            .login(userId: userId, userName: userName, userEmail: userEmail, providerType: providerType)
            .createRequest()
        let request = self.apiService.request(request: request)
        
        request.bind { [weak self] LoginResponseModel in
              self?.event.onNext(.login(loginResponseModel))
        }.disposedBag(disposedBag);

        return request
    }
}
```

2022-12-19 12:31 UTC, mooyoung2309 commented on FootprintIOS/FootprintIOS/Sources/ViewController/Login/LoginReactor.swift
> +                            KeychainHandler.shared.refreshToken = token.refreshToken
p5; 우선은 shared를 싱글톤으로 접근하는 방식이 나중에는 init에서 주입받은 KeychainHandler를 사용하는 방식으로 변경할 것 같습니다.

2022-12-26 10:43 UTC, 513sojin commented on FootprintIOS/FootprintIOS/Sources/Config/KeyChain.swift
> +
struct여야 하는 이유는 없습니다 . . 공통으로 접근 가능한 값이니까 class로 사용하는게 맞겠네요.  . !!

2022-12-26 10:43 UTC, 513sojin commented on FootprintIOS/FootprintIOS/Sources/Network/Foundation/BaseModel.swift
>  }
result값으로 string이 넘어와서 decode가 안되는 상태인데 어떻게 해야될지 더 고민해봐야겠어여 . .. .

<img width="311" alt="스크린샷 2022-12-25 오후 9 24 49" src="https://user-images.githubusercontent.com/54045865/209467824-f828d70a-fee0-4d4a-b403-76f3f23c11cb.png">

2022-12-26 10:43 UTC, 513sojin commented on FootprintIOS/FootprintIOS/Sources/Network/Login/LoginEndPoint.swift
> +            return Enviroment.apiBaseURL + "/users/auth/login"
<img width="621" alt="스크린샷 2022-12-25 오후 9 26 35" src="https://user-images.githubusercontent.com/54045865/209467872-b8b20f1d-fd15-414a-b1b8-00aa66dc8192.png">

이 부분 옛날에 네트워크 레이어 PR 올렸을 때 같이 올린 부분인데
plist에 넣어둔 값을 넣어두고 사용하고 있답니다 . .!

2022-12-26 10:43 UTC, 513sojin commented on FootprintIOS/FootprintIOS/Sources/Network/Foundation/APIManager.swift
> +                observable.onNext(responseData as! T)
이 부분은 따로 수정한게 있는데 까먹지 않고 회의때 같이 논의해보겠슴니다

2022-12-26 10:43 UTC, 513sojin commented on FootprintIOS/FootprintIOS/Sources/Network/Foundation/BaseModel.swift
>  }
이 부분도 회의 할 때 얘기해보려고 합니다 . .!!

2022-12-26 10:43 UTC, 513sojin commented on FootprintIOS/FootprintIOS/Sources/Network/Login/LoginManager.swift
> +    let apiService: APIManager
맞습니다 . . 참고했던 레포의 네이밍까지 생각없이 따라가버렸네요 . .
service와 manager가 혼용되고 있어서 바로 밑에 남겨주신 코드리뷰 이해가 좀 헷갈리는데 영모씨는 각각 단어를 어떤 의미로 생각하시는지 궁금합니다 . .!

저는 실제 request 날리는 APIManager 부분과 api를 정의하는 부분( ex)LoginManager파일 )  모두 ~Manager로 네이밍을 붙였는데

APIManager 부분을 제외하고 api를 정의하는 부분은 ~Service로 바꾸는게 나을까.. 하는 고민 중입니다 어떤가요 . .

2022-12-26 10:43 UTC, 513sojin commented on FootprintIOS/FootprintIOS/Sources/Network/Login/LoginManager.swift
> +
좋은 자료 감사합니다 !!

2022-12-27 15:57 UTC, mooyoung2309 approved these changes

2022-12-27 15:58 UTC, merged