[Feat/#52] 산책 기록 페이지 구현
UMC-1-Footprint/Footprint-iOS pull request #60
Opened 2023-01-04 08:25 UTC by 513sojin

## 📍 *Pull requests*

⛳️ **작업한 브랜치**
- feature/#52

📁 **작업한 내용**

- 산책 기록 페이지 개발
- 아직 세부적인 구현은 더 해야되는 상태입니당,, 리뷰 달아주시면 반영하면서 개발하겠습니다 

## 📢 참고 사항

### 싱글톤 사용
캘린더 부분에서 왼쪽, 오른쪽으로 넘어갈 때(달이 바뀔 때) calendarDate에 변화를 주고 이 값을 가져와서 사용했었는데요
(년, 월을 가져오는 Date 를 저장하고 있습니다)
```swift
struct State {
        var walkRecordSection: [WalkRecordSectionModel] = []
        let calendar = Calendar.current
        lazy var components = calendar.dateComponents([.year, .month], from: Date())
        lazy var calendarDate = calendar.date(from: components) ?? Date() // 이자식입니다 
        var monthTitle: String = .init()
        var isUpdated: Bool = false
    }
```
문제가 있다면,, 

예를 들어 밑의 코드에서 mutation을 방출할 때 순서대로 .setCalendarDate()가 실행돼서 state 값이 바뀌고 , 두 번째인 .setWalkRecord~ 가 실행돼서 state값이 바뀌는게 아니라 한 번에 reduce 함수에서 값을 업데이트 해주는 것 같습니다
```swift
case .prevMonth:
            return Observable.concat(
                [.just(.setCalendarDate(setPrevMonth())),
                 .just(.setWalkRecordSection(createCalendarSection(days: getDays(type: .prev)))),
                 .just(.setCalendarMonthTitle(updateMonthTitle()))
                ])
```
그래서 calendarDate 값이 업데이트 되었을 때 업데이트된 값을 가지고 section을 다시 만들어주어야 하는데
그게 안되다보니 calendarDate를 업데이트 해주는 mutation을 따로 방출했고 
실제로 사용하는 부분에서는 현재 calendarDate 값에서 추가적인 계산을 하여 사용했습니다.

위와 같은 방식으로 했을 때 중복된 코드를 계속 쓰게 되었고,, 
최종적으로는 싱글톤으로 빼서 사용하는 방식으로 변경했습니다. 이 방식 어떻게 생각하시는지 궁금합니다  !!

```swift 
class CalendarInfo {
    static let shared = CalendarInfo()
    
    let calendar = Calendar.current
    lazy var components = calendar.dateComponents([.year, .month], from: Date())
    lazy var calendarDate = calendar.date(from: components) ?? Date()
} 
````

**autoLayout 수정**
<img width="356" alt="스크린샷 2023-01-04 오후 5 19 14" src="https://user-images.githubusercontent.com/54045865/210512507-82340f4d-1f51-428e-a6a1-80e4a2c11074.png">

이 부분 영모씨 코드에서 재사용하고 있는데 imageView 쪽에서 자꾸 오토레이아웃 이슈 발생하길래 살짝 수정하였습니다 . .혹시라도 문제가 된다면 말해주세욥

## 📸 스크린샷
|기능|스크린샷|
|:--:|:--:|
|GIF|<img src = "https://user-images.githubusercontent.com/54045865/210512879-61b7a49b-fe5d-44c0-ae98-c657c397efe8.gif" width ="250">|

## 👣 관련 이슈
- Resolved: #52

2023-01-04 08:30 UTC, 513sojin commented on FootprintIOS/FootprintIOS/Sources/ViewController/WalkRecord/WalkRecordViewController.swift
> +    }
아 그리고 이 부분도, , 조언을 구하고 싶습니다
case 0 , case 1말고 section 이름으로 나누고 싶은데 방법이 떠오르질 않네요 ,,

2023-01-04 13:43 UTC, mooyoung2309 requested changes
고생 많으셨습니다. 이게 사실 리엑토 연결까지 고려한 설계를 하는게 어려웠을텐데.. 발전한 모습이 너무 잘 느껴져서 좋았습니다. 리뷰 반영해주시고 re-request 날려주시면 다시 확인하러 오겠습니다 ! 화이팅입니다..!

2023-01-04 13:43 UTC, annapo99 commented on FootprintIOS/FootprintIOS/Sources/CompositionRoot.swift
> +        let controller = MyPageViewController(pushMyFootprintScreen: pushMyFootprintScreen, pushWalkRecordScreen: pushWalkRecordScreen)
👍

2023-01-04 13:43 UTC, annapo99 commented on FootprintIOS/FootprintIOS/Sources/View/Record/Cell/RecordCollectionViewCell.swift
> +            $0.centerY.equalToSuperview()
화긴했습니다 !

2023-01-04 13:43 UTC, annapo99 commented on FootprintIOS/FootprintIOS/Sources/View/WalkRecord/WalkRecordCalendarHeader.swift
> +                $0.width.equalTo(8)
p2; setup 메소드 순서가 기존과 다른 것 같습니다. 이거는 동작상 아주 전혀 문제가 없지만, 가독성 측면에서 통일을 지켜주는게 좋아보입니다 ! 왜냐면 setup~~ 이거를 만든 이유가 가독성을 높이기 위함이었기 때문입니다 !

setupProperty -> setupHierachy -> setupLayout

2023-01-04 13:43 UTC, annapo99 commented on FootprintIOS/FootprintIOS/Sources/View/WalkRecord/WalkRecordCollectionViewCell.swift
> +    let footprintImage: UIImageView = .init()
+) 궁금한 사항 소진씨의 코드를 살펴보던 중 어떤거는 타입 추론 어떤거는 타입 어노테이션을 사용하셨는데, 어떤 기준으로 작성하나요 .. ?!

[참고 블로그](https://babbab2.tistory.com/14)

2023-01-04 13:43 UTC, annapo99 commented on FootprintIOS/FootprintIOS/Sources/View/WalkRecord/WalkRecordSummaryHeader.swift
> +        }
p2; 위와 같은 내용입니다 🥹

2023-01-04 13:43 UTC, mooyoung2309 commented on FootprintIOS/FootprintIOS/Sources/ViewController/MyPage/MyPageViewController.swift
>          super.init(nibName: nil, bundle: nil)
p4; init이 너무 아래에 있는 것 같습니다. 저도 정확한 컨벤션을 찾아봐야 알겠지만,, 

대충 UIKit의 코드를 보니깐, init이 상단에 있는 것을 확인했습니다,, 그렇다고 해서 이게 정답이다는 아니지만,, 고민해보셨으면 해서 남깁니다 ..! 언제나 소진씨 편입니다 .. 화이팅

```swift
@MainActor open class UIViewController : UIResponder, NSCoding, UIAppearanceContainer, UITraitEnvironment, UIContentContainer, UIFocusEnvironment {

    public init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)

    public init?(coder: NSCoder)

    open var view: UIView!

    open func loadView()
```

2023-01-04 13:43 UTC, mooyoung2309 commented on FootprintIOS/FootprintIOS/Sources/ViewController/MyPage/MyPageViewController.swift
> +    }
p3; 뷰컨간 로직은 가독성이 높게 같은 파일내에서 extension으로 빼서 작성하는 것을 추천드리고,, 

goTo ~~ 보다는 (사실 여기서 제가 goTo로 하긴 했습니다. 저의 나쁜 코드가 전염이 되기전에 ..)

willPushWalkRecordScreen~~ (네비게이션이동일때)
willPresentWalkRecordScreen~~ (모달 이동일때) 

이런식으로 네이밍 피드백 받아서 알려드립니다.. 저도 좋다고 생각했습니다 : D

2023-01-04 13:43 UTC, mooyoung2309 commented on FootprintIOS/FootprintIOS/Sources/ViewController/WalkRecord/WalkRecordReactor.swift
> +}
p1; 꼭 필요한 경우가 아니라면 싱글톤 패턴을 지양하는걸로 하려고 합니다. 🥺

싱글톤 패턴을 사용해야할 때의 명확한 기준은 없지만, 사실 싱글톤 패턴을 하나도 사용하지 않고 설계가 가능합니다. 안티 패턴이라고 하는 이유에는 여러 이유가 있겠지만, 그만큼 많이 사용하는 것도 여러 이유가 있다고 생각합니다. 하지만, 이런 객체지향적인 설계를 하다보면 조금 더 코드 작성하는데 도움이 될 것 같아서 사실 공부 목적 때문에 조금 더 이렇게 다루는게 좋다는 판단 뿐이었습니다 ..!

이 경우에는 WalkRecordReator 내부 변수로 선언해서 사용해도 좋을 듯 싶습니다. 

그렇지 않다면 의존성 주입으로 CalendarInfo를 Reactor init부분에 집어넣어도 좋을 듯 싶습니다. 

아니면 Calendar관련 로직에서 모두 필요하다면, CalendarService레이어를 두고 거기에서 로직처리를 해도 좋을 것 같습니다. 그리고 CompositionRoot에서 CalendarService레이어를 Reactor의 생성자에 주입 시키면 좋을 것 같습니다.

아니면 혹시 꼭 사용해야할 명확한 이유가 있으면 알려주시면 감사하겠습니다..! 🥺 😇

2023-01-04 13:43 UTC, mooyoung2309 commented on FootprintIOS/FootprintIOS/Sources/ViewController/WalkRecord/WalkRecordReactor.swift
> +}
아니면 다른 좀 더 좋은 방법을 고민하는 것도 좋아보입니다.

2023-01-04 13:43 UTC, mooyoung2309 commented on FootprintIOS/FootprintIOS/Sources/ViewController/WalkRecord/WalkRecordViewController.swift
> +        collectionView.register(WalkRecordSummaryHeader.self, forSupplementaryViewOfKind: UICollectionView.elementKindSectionHeader, withReuseIdentifier: String(describing: WalkRecordSummaryHeader.se
p5; 사실 지금은 잘 안쓰이는 것 같은데, setupDelegate() 라는 메소드도 포함되어있습니다. 저도 이렇게 한것같긴합니다 ..!

2023-01-04 13:43 UTC, mooyoung2309 commented on FootprintIOS/FootprintIOS/Sources/ViewController/WalkRecord/WalkRecordViewController.swift
> +    func createDataSource() -> WalkRecordDataSource {
p3; 이부분은 혹시 어떤 코드를 참고하신 걸까요 ? 궁금합니다 ..!

2023-01-04 13:43 UTC, mooyoung2309 commented on FootprintIOS/FootprintIOS/Sources/ViewController/WalkRecord/WalkRecordViewController.swift
> +    func createDataSource() -> WalkRecordDataSource {
createDataSource() 이부분입니다.

2023-01-04 13:43 UTC, mooyoung2309 commented on FootprintIOS/FootprintIOS/Sources/ViewController/WalkRecord/WalkRecordViewController.swift
> +    }
p4; (도움이 됐으면 좋겠습니다 ..!) 저는 상단에 dataSource를 선언해두고 인덱스 패스로 접근해서 스위치문을 사용하였습니다 !

```swift
    private lazy var dataSource = DataSource { [weak self] _, collectionView, indexPath, item -> UICollectionViewCell in 
//생략

    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        switch dataSource[indexPath.section].items[indexPath.row] {
        case let .tag(reactor):
            return CGSize(width: reactor.currentState.topic.size(withAttributes: [NSAttributedString.Key.font: JYPIOSFontFamily.Pretendard.medium.font(size: 16)]).width + 50, height: UI.tagCellHeight)
        case .emptyTag:
            return CGSize(width: 0, height: 0)
        case .pikmi:
            return CGSize(width: collectionView.frame.width - UI.cellWidthMargin, height: UI.pikmiCellHeight)
            
        case .createPikmi:
            return CGSize(width: collectionView.frame.width - UI.cellWidthMargin, height: UI.createPikmiCellHeight)
        }
    }

```

2023-01-04 13:45 UTC, mooyoung2309 commented on FootprintIOS/FootprintIOS/Sources/ViewController/WalkRecord/WalkRecordReactor.swift
> +}
위에 싱글톤 고민의 글을 방금 읽었었네요..  이부분은 제가 쓴 것 처럼 WalkRecordReactor 내부 변수로 추가해서 사용하시면 될것같습니다. 말씀하신대로 State의 변수로 추가하면 옵저버블한 값으로 따로 관리되기 때문에 문제가 있을수있어서입니다 ..!

2023-01-05 02:00 UTC, 0inn reviewed
이 사람 너무 잘한다 . . 뭐죠 ? header에 cell에 .. reactor까지 너무 야무져요
많이 배워갑니다 . . 멋져요

+)
앞으로 private이랑 final 키워드를 명시해서 구현하는 것이 좋을 것 같습니다. 
(저도 안했습니다. 앞으로 하겠습니다.)
가독성 측면과 성능 측면에서 무조건 좋다는 판단입니다 . . !

2023-01-05 02:00 UTC, 0inn commented on FootprintIOS/FootprintIOS/Sources/ViewController/WalkRecord/WalkRecordViewController.swift
> +    }
p4;

상속받는 BaseViewController에서 viewDidLoad를 오버라이딩해서 setup메서드 호출을 하고있는데 
이 뷰컨에서 또 오버라이딩한 이유가 있을까요 ?
이 뷰컨에서 viewDidLoad 시점에 수행해야 할 작업이 더 있지 않은 이상 지워도 될 것 같습니다 !

2023-01-05 02:00 UTC, 0inn commented on FootprintIOS/FootprintIOS/Sources/ViewController/WalkRecord/WalkRecordViewController.swift
> +                        .bind(to: reactor!.action)
p4;

강제 언래핑을 지양하는 것이 좋아보입니다.
여기서 강제 언래핑이 필수적인 다른 이유가 있나요 ?

2023-01-05 02:00 UTC, 0inn commented on FootprintIOS/FootprintIOS/Sources/ViewController/WalkRecord/WalkRecordViewController.swift
> +                        .disposed(by: header.disposeBag)
Q.

여기서 reactor.setNextMonth()를 매핑하고 .nextMonth를 매핑하는 이유는
PR에서 언급했던 것과 같이 mutation을 방출할 때 순서대로 방출하지 않기 때문일까요 ?

2023-01-05 02:00 UTC, 0inn commented on FootprintIOS/FootprintIOS/Sources/ViewController/WalkRecord/WalkRecordReactor.swift
> +}
저도 지금 상황에서 내부 변수 추가하는 방식 좋아보입니다 !

2023-01-05 08:54 UTC, 513sojin commented on FootprintIOS/FootprintIOS/Sources/View/WalkRecord/WalkRecordCollectionViewCell.swift
> +    let footprintImage: UIImageView = .init()
보통은 타입 어노테이션을 사용한다고 생각하는데,,, 사실 기준은 없습니다 . .좀 더 줏대를 가져볼까요 . . ?

2023-01-05 08:54 UTC, 513sojin commented on FootprintIOS/FootprintIOS/Sources/ViewController/WalkRecord/WalkRecordReactor.swift
> +}
calendar관련 로직에서 모두 필요한 것은 아니라서 내부 변수 사용하는 방법이 좋아보입니다 . . 
제가 싱글톤을 사용했던 이유는 State 외부에 변수를 추가하는 선택지를 생각해보지 못해서 떠올렸던 생각일뿐입니다,, (왤까요 ?.. state 변수에서 사용되지 않을거면 리액토를 사용하는 이유가 없다는 착각을 했던 것 같네요 . . ) 

특별한 이유가 없다면 싱글톤 패턴을 지양한다는 것도 처음 알게되었네요 정말 감사합니당 🥹

2023-01-05 08:54 UTC, 513sojin commented on FootprintIOS/FootprintIOS/Sources/ViewController/WalkRecord/WalkRecordViewController.swift
> +    }
훨씬 보기 좋아졌답니다 . .감사해요 🥹

2023-01-05 08:54 UTC, 513sojin commented on FootprintIOS/FootprintIOS/Sources/ViewController/WalkRecord/WalkRecordViewController.swift
> +    func createDataSource() -> WalkRecordDataSource {
구글링하다가 발견했는데요 지금 다시 찾으려니까 잘 안보이네요,, 혹시 이 방식과 밑의 코드처럼 선언하는 방식에 차이가 있을까요??

```swift
private lazy var dataSource = DataSource { [weak self] _, collectionView, indexPath, item -> UICollectionViewCell in
```

2023-01-08 13:12 UTC, 513sojin commented on FootprintIOS/FootprintIOS/Sources/ViewController/WalkRecord/WalkRecordViewController.swift
> +                        .bind(to: reactor!.action)
Nil-Coalescing을 사용하기 싫어서 강제 언래핑했는데 ,,, 옵셔널 바인딩 해서 사용하겠습니다 .. ^.^

2023-01-08 13:12 UTC, 513sojin commented on FootprintIOS/FootprintIOS/Sources/ViewController/WalkRecord/WalkRecordViewController.swift
> +                        .disposed(by: header.disposeBag)
코드 짤때 적절한 호출 시점을 못찾아서 버튼이 눌렸을 때 setNextMonth()함수 먼저 호출한 후에 reactor action 바인딩 해주었는데요

mutate 함수 내에서 호출하는 것으로 수정하였습니다

```swift 
func mutate(action: Action) -> Observable<Mutation> {
        switch action {
        case .refresh:
            return Observable.concat([
                .just(.setWalkRecordSection(createCalendarSection(days: getDays()))),
                .just(.setCalendarMonthTitle(updateMonthTitle()))
            ])
        case .prevMonth:
            setPrevMonth()
            return Observable.concat(
                [
                 .just(.setWalkRecordSection(createCalendarSection(days: getDays()))),
                 .just(.setCalendarMonthTitle(updateMonthTitle()))
                ])
        case .nextMonth:
            setNextMonth()
            return Observable.concat(
                [
                 .just(.setWalkRecordSection(createCalendarSection(days: getDays()))),
                 .just(.setCalendarMonthTitle(updateMonthTitle()))
                ])
        }
    }
```

2023-01-09 15:23 UTC, mooyoung2309 commented on FootprintIOS/FootprintIOS/Sources/View/WalkRecord/WalkRecordCollectionViewCell.swift
> +    let footprintImage: UIImageView = .init()
줏대라기 보다는(살짝은 부정적인 단어 . . ?! ) .. 통일성을 지키는 것은 코드를 작성할때 도움이 될것같습니다 ! 왜냐면 이거는 자신만의 지키고 싶은 스타일이 될 수 있기 때문입니다

2023-01-09 15:24 UTC, mooyoung2309 approved these changes
고생 많으셨습니다 ! 소진씨도 열심히시네요 .. ! 호주는 조심히 가시길 ~..

2023-01-09 15:28 UTC, merged